# Generated by Django 3.1.7 on 2021-04-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210411_0420'),
        ('accounts', '0004_auto_20210414_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='project',
            field=models.ManyToManyField(blank=True, to='api.Project'),
        ),
    ]
