# Pull base image
FROM python:3.8-slim-buster

ENV PATH="/scripts:${PATH}"

# Create and Set working directory
RUN useradd app -m -d /app \
    && chmod -R 755 /app

WORKDIR /app

#expoose the port for dokku
EXPOSE 8000

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PORT=8000

RUN apt-get update \
    && apt-get install gcc python3-dev libpq-dev -y  \
    && pip install --upgrade pip \
    && pip install pipenv \
    && apt-get clean

COPY Pipfile Pipfile.lock .
RUN pipenv lock --keep-outdated --requirements > requirements.txt
RUN pip install -r requirements.txt

# Copy project
COPY . .

RUN chmod +x /app/scripts/*

##run in container as unprivileged app user
USER app

ENTRYPOINT ["/scripts/entrypoint.sh"]