version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python /app/manage.py runserver 0.0.0.0:8000'
    env_file:
      - envs/dev.env
    stdin_open: true
    tty: true
    volumes:
      - '.:/app'
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
volumes:
  postgres_data:
