version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_prod
    environment:
      - ENVIRONMENT=development
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
