# Generated by Django 3.1.7 on 2021-04-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210403_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issueType',
            field=models.IntegerField(choices=[(1, 'Task'), (2, 'Bug'), (3, 'Story')], default=1, verbose_name='Issue Type'),
        ),
    ]
