# Generated by Django 3.1.7 on 2021-04-06 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210405_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueimage',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_images', to='api.issue'),
        ),
    ]
