# Generated by Django 3.1.7 on 2021-04-10 16:24

import apps.api.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210406_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('can_view', 'can_view'),)},
        ),
        migrations.AlterField(
            model_name='commentimage',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_images', to='api.comment'),
        ),
        migrations.AlterField(
            model_name='commentimage',
            name='comment_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=apps.api.models.PathAndRename('issue_images')),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.project'),
        ),
        migrations.AlterField(
            model_name='issueimage',
            name='issue_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=apps.api.models.PathAndRename('issue_images')),
        ),
    ]
